#!/usr/bin/env bun
/**
 * embed-assets.ts — Generate TypeScript constants from prompt .md and model .toml files.
 *
 * Outputs:
 *   packages/cli/src/prompts/embedded.ts
 *   packages/runtime/src/engine/prompts/embedded.ts
 *   packages/runtime/src/core/embedded-models.ts
 *
 * Run: bun run scripts/embed-assets.ts
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");

function writeLine(message: string): void {
  process.stdout.write(`${message}\n`);
}

function escapeTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function toConstName(filename: string): string {
  return "PROMPT_" + filename
    .replace(/\.md$/, "")
    .replace(/-/g, "_")
    .toUpperCase();
}

// ── CLI prompts ─────────────────────────────────────────────

const cliPromptsDir = join(ROOT, "packages/cli/src/prompts");
const cliPromptFiles = ["base.md", "tools.md", "mode-act.md", "review.md"];
const cliLines = [
  "// Generated by scripts/embed-assets.ts — do not edit manually.",
  "",
];
for (const file of cliPromptFiles) {
  const content = readFileSync(join(cliPromptsDir, file), "utf-8");
  const name = toConstName(file);
  cliLines.push(`export const ${name} = \`${escapeTemplate(content)}\`;`);
  cliLines.push("");
}
writeFileSync(join(cliPromptsDir, "embedded.ts"), cliLines.join("\n"));
writeLine(`✓ CLI prompts: ${cliPromptFiles.length} files → packages/cli/src/prompts/embedded.ts`);

// ── Runtime agent prompts ───────────────────────────────────

const runtimePromptsDir = join(ROOT, "packages/runtime/src/engine/prompts");
const runtimePromptFiles = [
  "agent-common.md", "agent-general.md", "agent-architect.md",
  "agent-explore.md", "agent-reviewer.md",
];
const rtLines = [
  "// Generated by scripts/embed-assets.ts — do not edit manually.",
  "",
];
for (const file of runtimePromptFiles) {
  const content = readFileSync(join(runtimePromptsDir, file), "utf-8");
  const name = toConstName(file);
  rtLines.push(`export const ${name} = \`${escapeTemplate(content)}\`;`);
  rtLines.push("");
}
writeFileSync(join(runtimePromptsDir, "embedded.ts"), rtLines.join("\n"));
writeLine(`✓ Agent prompts: ${runtimePromptFiles.length} files → packages/runtime/src/engine/prompts/embedded.ts`);

// ── Model TOML files ────────────────────────────────────────

const modelsDir = join(ROOT, "models");
const tomlFiles = readdirSync(modelsDir).filter((f) => f.endsWith(".toml")).sort();
const modelLines = [
  "// Generated by scripts/embed-assets.ts — do not edit manually.",
  "",
  "/** Raw TOML content keyed by filename (e.g. \"anthropic.toml\"). */",
  "export const EMBEDDED_MODEL_TOML: Record<string, string> = {",
];
for (const file of tomlFiles) {
  const content = readFileSync(join(modelsDir, file), "utf-8");
  modelLines.push(`  ${JSON.stringify(file)}: ${JSON.stringify(content)},`);
}
modelLines.push("};");
modelLines.push("");
writeFileSync(
  join(ROOT, "packages/runtime/src/core/embedded-models.ts"),
  modelLines.join("\n"),
);
writeLine(`✓ Models: ${tomlFiles.length} files → packages/runtime/src/core/embedded-models.ts`);
