# Provider configurations for benchmarking
providers:
  # DeepSeek Direct requires a different API key (not OpenRouter key)
  # Uncomment and add DeepSeek API key to .devagent.toml to enable
  # - name: "DeepSeek Direct"
  #   provider: "deepseek"
  #   model: "deepseek-chat"
  #   api_key_env: "DEVAGENT_API_KEY"
  #   base_url: "https://api.deepseek.com/v1"

  - name: "OpenRouter - Claude Sonnet 4.5"
    provider: "openrouter"
    model: "anthropic/claude-sonnet-4.5"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"
    max_completion_tokens: 4096

  - name: "OpenRouter - DeepSeek v3.1 Free"
    provider: "openrouter"
    model: "deepseek/deepseek-chat-v3.1:free"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - GPT OSS 120B (Groq)"
    provider: "openrouter"
    model: "openai/gpt-oss-120b"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - GPT-5"
    provider: "openrouter"
    model: "openai/gpt-5"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Nvidia Nemotron Nano Free"
    provider: "openrouter"
    model: "nvidia/nemotron-nano-9b-v2:free"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  # New models to benchmark
  - name: "OpenRouter - GLM 4.6"
    provider: "openrouter"
    model: "z-ai/glm-4.6"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - DeepSeek v3.2 Exp"
    provider: "openrouter"
    model: "deepseek/deepseek-v3.2-exp"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Qwen3 VL 235B"
    provider: "openrouter"
    model: "qwen/qwen3-vl-235b-a22b-instruct"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Qwen3 Coder Plus"
    provider: "openrouter"
    model: "qwen/qwen3-coder-plus"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - GPT-5 Codex"
    provider: "openrouter"
    model: "openai/gpt-5-codex"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Grok 4 Fast"
    provider: "openrouter"
    model: "x-ai/grok-4-fast"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Grok Code Fast 1"
    provider: "openrouter"
    model: "x-ai/grok-code-fast-1"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - GPT-4.1 Mini"
    provider: "openrouter"
    model: "openai/gpt-4.1-mini"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - GPT OSS 20B"
    provider: "openrouter"
    model: "openai/gpt-oss-20b"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Qwen3 Coder 30B"
    provider: "openrouter"
    model: "qwen/qwen3-coder-30b-a3b-instruct"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Llama 3.3 70B"
    provider: "openrouter"
    model: "meta-llama/llama-3.3-70b-instruct"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Phi-4 Multimodal Instruct"
    provider: "openrouter"
    model: "microsoft/phi-4-multimodal-instruct"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

  - name: "OpenRouter - Llama 4 Scout"
    provider: "openrouter"
    model: "meta-llama/llama-4-scout"
    api_key_env: "DEVAGENT_API_KEY"
    base_url: "https://openrouter.ai/api/v1"

# Default benchmark settings
default_settings:
  timeout: 120  # seconds
  max_iterations: 20
  auto_approve_code: true
  runs_per_test: 1  # Number of times to run each test (for averaging)
